SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MB-CRM-DEV_MalibuDev_MSCRM_col_warrantyregistration]
AS
SELECT [Alt_Id],[col_AvalaModifiedDate],[col_BoatId],[col_BoatIdName],[col_BoatOwnerId],[col_BoatOwnerIdName],[col_BoatOwnerIdYomiName],[col_BoatTrailerId],[col_BoatTrailerIdName],[col_CurrentCustomerCity],[col_CurrentCustomerCountry],[col_CurrentCustomerCountryName],[col_CurrentCustomerEmailAddress],[col_CurrentCustomerFax],[col_CurrentCustomerFirstName],[col_CurrentCustomerLastName],[col_CurrentCustomerMiddleName],[col_CurrentCustomerPhone],[col_CurrentCustomerPostalCode],[col_CurrentCustomerProvince],[col_CurrentCustomerState],[col_CurrentCustomerStreetAddress],[col_CurrentCustomerStreetAddress2],[col_CurrentSecondaryOwnerEmail],[col_currentsecondaryownerfirstname],[col_CurrentSecondaryOwnerLastName],[col_CurrentSecondaryOwnerMiddleName],[col_CurrentSecondaryOwnerPhone],[col_DateResold],[col_DateSold],[col_DealerContactCreatedBy],[col_DealerContactCreatedByName],[col_DealerContactCreatedByYomiName],[col_DealerContactModifiedBy],[col_DealerContactModifiedByName],[col_DealerContactModifiedByYomiName],[col_DebugData],[col_DeliveredDate],[col_DeliveryDate],[col_HullIdentificationNumber],[col_name],[col_OriginalCustomerCity],[col_OriginalCustomerCountry],[col_OriginalCustomerCountryName],[col_OriginalCustomerEmailAddress],[col_OriginalCustomerFax],[col_OriginalCustomerFirstName],[col_OriginalCustomerLastName],[col_OriginalCustomerMiddleName],[col_OriginalCustomerPhone],[col_OriginalCustomerPostalCode],[col_OriginalCustomerProvince],[col_OriginalCustomerState],[col_OriginalCustomerStreet],[col_OriginalCustomerStreetAddress2],[col_OriginalOwner],[col_OriginalSecondaryOwnerEmail],[col_OriginalSecondaryOwnerFirstName],[col_OriginalSecondaryOwnerLastName],[col_OriginalSecondaryOwnerMiddleName],[col_OriginalSecondaryOwnerPhone],[col_PurchasingDealer],[col_PurchasingDealerName],[col_PurchasingDealerYomiName],[col_ServicingDealer],[col_ServicingDealerName],[col_ServicingDealerYomiName],[col_warrantyregistrationId],[col_WarrantyTransfer],[CreatedBy],[CreatedByName],[CreatedByYomiName],[CreatedOn],[CreatedOnBehalfBy],[CreatedOnBehalfByName],[CreatedOnBehalfByYomiName],[ImportSequenceNumber],[ModifiedBy],[ModifiedByName],[ModifiedByYomiName],[ModifiedOn],[ModifiedOnBehalfBy],[ModifiedOnBehalfByName],[ModifiedOnBehalfByYomiName],[new_BoatEngineId],[new_BoatEngineIdName],[new_CardID],[new_DateDelivered],[new_LaborExpirationDate],[new_NewOwnerGiftName],[new_QuoteDiscountId],[new_QuoteDiscountIdName],[new_WarrantyEndDate],[new_WarrantyStartDate],[new_WarrantyType],[OverriddenCreatedOn],[OwnerId],[OwnerIdDsc],[OwnerIdName],[OwnerIdType],[OwnerIdYomiName],[OwningBusinessUnit],[OwningTeam],[OwningUser],[statecode],[statuscode],[TimeZoneRuleVersionNumber],[UTCConversionTimeZoneCode],[VersionNumber] FROM [MB-CRM-DEV].[MalibuDev_MSCRM].[dbo].[col_warrantyregistration]
 WITH (NOLOCK);
GO
