SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[MBUU-STGDB01_WTSData_tblAVALADealers]
AS
SELECT [AVALADEALERID],[PRODUCT],[DATEREPORTED],[ACTION],[DLRNUMBR],[DLRLOCTN],[DLRNAME],[DLRGNAME],[PCONTACT],[ADDRES1],[ADDRES2],[CITY],[STATE],[POSTCODE],[COUNTRY],[PHONE],[FAX],[EMAIL],[URL],[REGION],[TERRITORY],[DISTRICT],[BRANDS],[DEALERTYPE] FROM [WTSData].[dbo].[tblAVALADealers]
 WITH (NOLOCK);
GO
