SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[SPORTSTERTEST_MA05_SOP10102]
AS
SELECT [SOPTYPE],[SOPNUMBE],[SEQNUMBR],[DISTTYPE],[DistRef],[ACTINDX],[DEBITAMT],[ORDBTAMT],[CRDTAMNT],[ORCRDAMT],[CURRNIDX],[TRXSORCE],[POSTED],[Contract_Exchange_Rate],[DEX_ROW_ID] FROM [SPORTSTERTEST].[MA05].[dbo].[SOP10102]
 WITH (NOLOCK);
GO
