SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MB-CRM-DEV_MalibuDev_MSCRM_QuoteDetail]
AS
SELECT [Alt_Id],[BaseAmount],[BaseAmount_Base],[col_AxisSurfGateColor],[col_FeatureApprovalId],[col_FeatureApprovalIdName],[col_FeatureClass],[col_InteriorScheme],[col_NeedApproval],[col_PortalGridPlaceholder1],[col_PortalGridPlaceholder2],[col_PortalGridPlaceholder3],[col_PortalGridPlaceholder4],[col_QuantityBackOrdered],[col_QuantityInvoiced],[col_RetailPrice],[col_retailprice_Base],[col_ReturnClaimExtendedAmount],[col_returnclaimextendedamount_Base],[col_ShipToWarehouse],[col_TierOneAmount],[col_tieroneamount_Base],[col_TierThreeAmount],[col_tierthreeamount_Base],[col_TierTwoAmount],[col_tiertwoamount_Base],[col_TrlrGPItemNumber],[col_WarehouseOverride],[col_WarehouseOverrideName],[CreatedBy],[CreatedByName],[CreatedByYomiName],[CreatedOn],[CreatedOnBehalfBy],[CreatedOnBehalfByName],[CreatedOnBehalfByYomiName],[Description],[ExchangeRate],[exp_linenumber],[exp_nestedlinenumber],[exp_recordid],[ExtendedAmount],[ExtendedAmount_Base],[ImportSequenceNumber],[IsDeleted],[IsPriceOverridden],[IsProductOverridden],[LineItemNumber],[ManualDiscountAmount],[ManualDiscountAmount_Base],[ModifiedBy],[ModifiedByName],[ModifiedByYomiName],[ModifiedOn],[ModifiedOnBehalfBy],[ModifiedOnBehalfByName],[ModifiedOnBehalfByYomiName],[new_AlbumName],[new_AxisScheme],[new_Category],[new_Color],[new_CustomInput],[new_DeckScheme],[new_Edition],[new_Feature],[new_GPItemNumber],[new_GPUoM],[new_HullScheme],[new_Model],[new_ModelYear],[new_Package],[new_ParentItem],[new_PrintWindowSticker],[new_PrintWorkOrder],[new_Series],[OverriddenCreatedOn],[OwnerId],[OwnerIdType],[OwningBusinessUnit],[OwningUser],[ParentBundleId],[PricePerUnit],[PricePerUnit_Base],[PricingErrorCode],[ProductAssociationId],[ProductDescription],[ProductId],[ProductIdName],[ProductTypeCode],[PropertyConfigurationStatus],[Quantity],[QuoteDetailId],[QuoteId],[QuoteIdName],[QuoteStateCode],[RequestDeliveryBy],[SalesRepId],[SalesRepIdName],[SalesRepIdYomiName],[SequenceNumber],[ShipTo_AddressId],[ShipTo_City],[ShipTo_ContactName],[ShipTo_Country],[ShipTo_Fax],[ShipTo_FreightTermsCode],[ShipTo_Line1],[ShipTo_Line2],[ShipTo_Line3],[ShipTo_Name],[ShipTo_PostalCode],[ShipTo_StateOrProvince],[ShipTo_Telephone],[Tax],[Tax_Base],[TimeZoneRuleVersionNumber],[TransactionCurrencyId],[TransactionCurrencyIdName],[UoMId],[UoMIdName],[UTCConversionTimeZoneCode],[VersionNumber],[VolumeDiscountAmount],[VolumeDiscountAmount_Base],[WillCall] FROM [MB-CRM-DEV].[MalibuDev_MSCRM].[dbo].[QuoteDetail]
 WITH (NOLOCK);
GO
