SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[MBUU-STGDB01_SL_FL_App_job_mst]
AS
SELECT [site_ref],[type],[job],[suffix],[job_date],[cust_num],[ord_type],[ord_num],[ord_line],[ord_release],[est_job],[est_suf],[item],[qty_released],[qty_complete],[qty_scrapped],[stat],[lst_trx_date],[root_job],[root_suf],[ref_job],[ref_suf],[ref_oper],[ref_seq],[low_level],[effect_date],[wip_acct],[wip_total],[wip_complete],[wip_special],[revision],[picked],[whse],[jcb_acct],[ps_num],[wip_lbr_acct],[wip_fovhd_acct],[wip_vovhd_acct],[wip_out_acct],[wip_matl_total],[wip_lbr_total],[wip_fovhd_total],[wip_vovhd_total],[wip_out_total],[wip_matl_comp],[wip_lbr_comp],[wip_fovhd_comp],[wip_vovhd_comp],[wip_out_comp],[rollup_date],[wip_acct_unit1],[wip_acct_unit2],[wip_acct_unit3],[wip_acct_unit4],[jcb_acct_unit1],[jcb_acct_unit2],[jcb_acct_unit3],[jcb_acct_unit4],[wip_lbr_acct_unit1],[wip_lbr_acct_unit2],[wip_lbr_acct_unit3],[wip_lbr_acct_unit4],[wip_fovhd_acct_unit1],[wip_fovhd_acct_unit2],[wip_fovhd_acct_unit3],[wip_fovhd_acct_unit4],[wip_vovhd_acct_unit1],[wip_vovhd_acct_unit2],[wip_vovhd_acct_unit3],[wip_vovhd_acct_unit4],[wip_out_acct_unit1],[wip_out_acct_unit2],[wip_out_acct_unit3],[wip_out_acct_unit4],[prod_mix],[NoteExistsFlag],[RecordDate],[RowPointer],[description],[config_id],[co_product_mix],[CreatedBy],[UpdatedBy],[CreateDate],[InWorkflow],[scheduled],[rcpt_rqmt],[export_type],[contains_tax_free_matl],[midnight_of_job_sch_end_date],[midnight_of_job_sch_compdate],[rework],[unlinked_xref],[Uf_S2_ItemCategory],[Uf_S2_Location],[Uf_S2_NestCompleted],[Uf_S2_PickToNest],[Uf_S2_MoldNo],[Uf_S2_ReprintComplete],[Uf_S2_ReprintNeeded],[Uf_S2_PrevNest],[Uf_S2_DoNotDelete],[Uf_S2_RePick],[Uf_S2_AssignedTo],[Uf_S2_BOMComplete],[Uf_S2_BuildDoc],[Uf_S2_Comment],[Uf_S2_DesignInfo],[Uf_S2_MatlReady],[Uf_S2_PatternProgram],[Uf_S2_SubJobDone],[Uf_S2_BatchNo],[Uf_S2_Printed],[prospect_id],[is_external],[preassign_lots],[preassign_serials],[config_doc_id],[MO_bom_alternate_id],[MO_bom_alternate_description],[MO_co_job],[MO_product_cycle],[MO_qty_per_cycle],[MO_job_description] FROM [SL_FL_App].[dbo].[job_mst]
 WITH (NOLOCK);
GO
