SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MB-CRM-DEV_MalibuDev_MSCRM_col_boat]
AS
SELECT [Alt_Id],[col_ActiveWarrantyId],[col_ActiveWarrantyIdName],[col_AuthorizationNumber],[col_BoatBrandId],[col_BoatBrandIdName],[col_boatId],[col_BoatModelId],[col_BoatModelIdName],[col_BoatOrderId],[col_BoatOrderIdName],[col_BoatQuoteId],[col_BoatQuoteIdName],[col_BoatsId],[col_BoatsIdName],[col_CurrentOwner],[col_CurrentOwnerName],[col_CurrentOwnerYomiName],[col_DateDelivered],[col_DealerLocked],[col_EngineSerialNumber],[col_EstimatedShipDate],[col_GalvanizedTrailer],[col_HistoricalOrderNumber],[col_HullID],[col_HullType],[col_IntegrateSprayDate],[col_InvoiceDate],[col_InvoiceId],[col_InvoiceIdName],[col_LaborExpirationDate],[col_LegacyBoatModel],[col_LegacyOrderDesription],[col_LegacyOrderID],[col_MasterNumber],[col_MigrationDate],[col_MOAttempted],[col_ModelYears],[col_MONumber],[col_name],[col_OrderNumber],[col_OriginalOwner],[col_OriginalOwnerName],[col_OriginalOwnerYomiName],[col_PerformTransfer],[col_PlaceholderPortalQuoteTotalAmount],[col_PurchaseDealer],[col_PurchaseDealerName],[col_PurchaseDealerYomiName],[col_QuoteSubmitted],[col_ServiceDealer],[col_ServiceDealerName],[col_ServiceDealerYomiName],[col_ShipDate],[col_ShipmentId],[col_ShipmentIdName],[col_SlotDate],[col_SlotNumber],[col_SoldDate],[col_SprayDate],[col_TrailerId],[col_TrailerIdName],[col_TrailerSerialNumber],[col_WarrantryTransferDate],[col_WarrantyExpirationDate],[col_WarrantyRegistrationDate],[col_WarrantyStartDate],[col_WindowSticker],[CreatedBy],[CreatedByName],[CreatedByYomiName],[CreatedOn],[CreatedOnBehalfBy],[CreatedOnBehalfByName],[CreatedOnBehalfByYomiName],[ImportSequenceNumber],[ModifiedBy],[ModifiedByName],[ModifiedByYomiName],[ModifiedOn],[ModifiedOnBehalfBy],[ModifiedOnBehalfByName],[ModifiedOnBehalfByYomiName],[new_BoatEngineId],[new_BoatEngineIdName],[new_CurrentOwner],[new_OriginalOwner],[new_ServiceBulletinDetailId],[new_ServiceBulletinDetailIdName],[OverriddenCreatedOn],[OwnerId],[OwnerIdDsc],[OwnerIdName],[OwnerIdType],[OwnerIdYomiName],[OwningBusinessUnit],[OwningTeam],[OwningUser],[statecode],[statuscode],[TimeZoneRuleVersionNumber],[UTCConversionTimeZoneCode],[VersionNumber] FROM [MB-CRM-DEV].[MalibuDev_MSCRM].[dbo].[col_boat]
 WITH (NOLOCK);
GO
