SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[SPORTSTERTEST_MA05_SOP10201]
AS
SELECT [SOPTYPE],[SOPNUMBE],[LNITMSEQ],[CMPNTSEQ],[QTYTYPE],[SERLTNUM],[SERLTQTY],[SLTSQNUM],[DATERECD],[DTSEQNUM],[UNITCOST],[ITEMNMBR],[TRXSORCE],[POSTED],[OVRSERLT],[BIN],[MFGDATE],[EXPNDATE],[DEX_ROW_ID] FROM [SPORTSTERTEST].[MA05].[dbo].[SOP10201]
 WITH (NOLOCK);
GO
